export { accountFixture, inboxFixture } from "./fixtures.ts";

export {
  createProviderPageSchema,
  inboxMessagePageSchema,
  inboxMessageSchema,
  inboxResponseSchema,
  mailAccountPageSchema,
  mailAccountSchema,
  mailContactSchema,
  mailProviderSchema,
  meResponseSchema,
  normalizedLabelPageSchema,
  normalizedLabelSchema,
  normalizedMessagePageSchema,
  normalizedMessageRawSchema,
  normalizedMessageSchema,
  normalizedThreadPageSchema,
  normalizedThreadSchema,
  providerPageShapeSchema,
} from "./schemas.ts";

export type {
  InboxMessage,
  InboxMessagePage,
  InboxResponse,
  MailAccount,
  MailAccountPage,
  MailContact,
  MailProvider,
  MailProviderClient,
  MeResponse,
  NormalizedLabel,
  NormalizedLabelPage,
  NormalizedMessage,
  NormalizedMessagePage,
  NormalizedMessageRaw,
  NormalizedThread,
  NormalizedThreadPage,
  ProviderPage,
} from "./schemas.ts";
