export { accountFixture, authSessionFixture, inboxFixture } from "./fixtures.ts";

export {
  authSessionSchema,
  authUserSchema,
  createProviderPageSchema,
  inboxMessagePageSchema,
  inboxMessageSchema,
  inboxQuerySchema,
  inboxResponseSchema,
  mailAccountPageSchema,
  mailAccountSchema,
  mailContactSchema,
  mailProviderSchema,
  meResponseSchema,
  normalizedLabelPageSchema,
  normalizedLabelSchema,
  normalizedMessagePageSchema,
  normalizedMessageRawSchema,
  normalizedMessageSchema,
  normalizedThreadPageSchema,
  normalizedThreadSchema,
  providerPageShapeSchema,
  syncStateSchema,
  syncStatusSchema,
} from "./schemas.ts";

export type {
  AuthSession,
  AuthUser,
  InboxMessage,
  InboxMessagePage,
  InboxQuery,
  InboxResponse,
  MailAccount,
  MailAccountPage,
  MailContact,
  MailProvider,
  MailProviderClient,
  MeResponse,
  NormalizedLabel,
  NormalizedLabelPage,
  NormalizedMessage,
  NormalizedMessagePage,
  NormalizedMessageRaw,
  NormalizedThread,
  NormalizedThreadPage,
  ProviderPage,
  SyncState,
  SyncStatus,
} from "./schemas.ts";
