import { z } from "zod";
import { attentionRoutingTargetSchema, attentionRoutingQuerySchema } from "./attention-routing.ts";
const id = z.string().trim().min(1).max(256);
const revision = z.number().int().positive();
import { destinationResolutionSchema } from "./destination-resolution.ts";
export { destinationResolutionSchema } from "./destination-resolution.ts";
export const mailDestinationSchema = z.object({ id, isFallback: z.boolean(), name: z.string(), position: z.number().int(), retiredAt: z.string().nullable(), revision, notificationPreference: z.enum(["notify", "badge", "quiet"]), delivery: z.literal("proposal_only"), counts: z.object({ total: z.number().int().nonnegative(), unread: z.number().int().nonnegative() }) }).strict();
export const destinationListSchema = z.object({ revision, fallbackDestinationId: id, destinations: z.array(mailDestinationSchema) }).strict();
export const destinationCreateSchema = z.object({ expectedRevision: revision, name: z.string().trim().min(1).max(120) }).strict();
export const destinationUpdateSchema = z.object({ expectedRevision: revision, name: z.string().trim().min(1).max(120).optional(), position: z.number().int().nonnegative().optional(), notificationPreference: z.enum(["notify", "badge", "quiet"]).optional() }).strict().refine(v => v.name !== undefined || v.position !== undefined || v.notificationPreference !== undefined, "Choose a change");
export const destinationRetireSchema = z.object({ expectedRevision: revision, reassignToDestinationId: id }).strict();
export const destinationRoutingQuerySchema = attentionRoutingQuerySchema;
export const destinationRoutingChangeSchema = z.object({ expectedRevision: revision, target: attentionRoutingTargetSchema, destinationId: id.nullable() }).strict();
export const destinationRoutingStateSchema = z.object({ accountId: id, revision, selection: z.object({ target: attentionRoutingTargetSchema, explicitDestinationId: id.nullable(), effective: destinationResolutionSchema, inherited: destinationResolutionSchema }).strict() }).strict();
export const destinationRoutingResultSchema = z.object({ state: destinationRoutingStateSchema, undo: destinationRoutingChangeSchema }).strict();
export type MailDestination = z.infer<typeof mailDestinationSchema>;
export type DestinationRoutingState = z.infer<typeof destinationRoutingStateSchema>;
export type DestinationRoutingChange = z.infer<typeof destinationRoutingChangeSchema>;
export type DestinationResolution = z.infer<typeof destinationResolutionSchema>;
