import SwiftUI

struct ThreadView: View {
    @EnvironmentObject var state: AppState; let message: InboxMessage; @State private var detail: ThreadDetail?; @State private var error: String?; @State private var shareURL: URL?
    var body: some View { ScrollView { if let detail { LazyVStack(alignment: .leading, spacing: 16) { ForEach(detail.messages) { item in VStack(alignment: .leading, spacing: 10) { HStack { ContactGlyph(contact: item.from); VStack(alignment: .leading) { Text(item.from.name ?? item.from.email).font(.headline); Text(item.receivedAt).font(.caption).foregroundStyle(.secondary) } }; if let html = item.bodyHtml, !html.isEmpty { SafeHTMLView(html: html).frame(minHeight: 180) } else { Text(item.bodyText ?? item.snippet).textSelection(.enabled) }; ForEach(item.attachments) { attachment in Button { Task { await download(attachment) } } label: { Label("\(attachment.filename) · \(ByteCountFormatter.string(fromByteCount: Int64(attachment.size), countStyle: .file))", systemImage: "paperclip") }.buttonStyle(.bordered) }; Divider() }.padding(.horizontal) } }.padding(.vertical) } else if let error { ContentUnavailableView("Conversation unavailable", systemImage: "exclamationmark.bubble", description: Text(error)); Button("Try again") { Task { await load() } } } else { ProgressView("Getting conversation").padding(.top, 80) } }
        .navigationTitle(detail?.thread.subject ?? message.subject).navigationBarTitleDisplayMode(.inline)
        .toolbar { if let detail { ToolbarItemGroup(placement: .bottomBar) { NavigationLink(destination: ComposeView(context: detail, kind: "reply")) { Label("Reply", systemImage: "arrowshape.turn.up.left") }; Spacer(); NavigationLink(destination: ComposeView(context: detail, kind: "reply_all")) { Label("Reply all", systemImage: "arrowshape.turn.up.left.2") }; Spacer(); NavigationLink(destination: ComposeView(context: detail, kind: "forward")) { Label("Forward", systemImage: "arrowshape.turn.up.right") } } } }
        .task { await load() }.sheet(isPresented: .constant(shareURL != nil), onDismiss: { shareURL = nil }) { if let shareURL { ShareSheet(items: [shareURL]) } }
    }
    func load() async { guard !state.demoMode else { error = "Demo conversations are list-only."; return }; guard let client = state.client else { return }; do { detail = try await client.thread(message.threadId, accountId: message.accountId); try? await client.markRead(message.threadId, accountId: message.accountId) } catch { self.error = error.localizedDescription } }
    func download(_ attachment: MailAttachment) async { guard let client = state.client else { return }; do { let data = try await client.attachment(attachment.id, accountId: message.accountId); let dir = FileManager.default.temporaryDirectory.appending(path: UUID().uuidString); try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true); let url = dir.appending(path: attachment.filename); try data.write(to: url, options: [.atomic, .completeFileProtection]); shareURL = url } catch { self.error = error.localizedDescription } }
}
struct ShareSheet: UIViewControllerRepresentable { let items: [Any]; func makeUIViewController(context: Context) -> UIActivityViewController { UIActivityViewController(activityItems: items, applicationActivities: nil) }; func updateUIViewController(_ controller: UIActivityViewController, context: Context) {} }

